export default [
  { id: 1, value: "On t'entend pas t'es sur mute" },
  { id: 3, value: "Colis en retard ou presque" },
  { id: 4, value: "Un bébé tenu comme Simba devant la webcam" },
  { id: 15, value: "Quelqu'un a une mauvaise connexion" },
  { id: 2, value: "Nouvelle souche plus contagieuse" },
  { id: 19, value: "Potin de voisinage délinquant" },
  { id: 20, value: "On pourrait se rencontrer au centre d'achat" },
  { id: 21, value: "Compter jusqu'à 3 avant un screenshot" },
  { id: 23, value: "Je reviens, je vais aux toilettes" },
  { id: 24, value: "Ça va fêter fort en 2021" },

  { id: 18, value: "Louise devient rouge à cause du vin" },
  { id: 10, value: "Le iPad à Mamie qui bug" },
  { id: 11, value: "Mamie reçoit un Danielle Steele" },
  { id: 7, value: "Mamie reçoit un Grand Marnier" },
  { id: 8, value: "Conversation sur la comptabilité" },
  { id: 12, value: "Conversation sur les Apple Watch" },
  { id: 13, value: "François fait un jeu de mot" },
  { id: 14, value: "Martin fait une joke plate" },
  { id: 16, value: "Conversation sur le fait que JP travaille trop" },
  { id: 5, value: "Étienne dit un mot sophistiqué" },
  { id: 9, value: "Monique montre son désaccord" },
  { id: 17, value: "Into the Miss PoonSpoon" },
  { id: 6, value: "Steph s'endort" },
  { id: 22, value: `Louise dit qu'elle est gênée d'ouvrir son cadeau "comme jeep"` },
];
