export default [
  { id: 1, value: "On t'entend pas t'es sur mute" },
  { id: 2, value: "Nouvelle souche plus contagieuse" },
  { id: 3, value: "Martin fait une joke plate" },
  { id: 4, value: "Un bébé tenu comme Simba devant la webcam" },
  { id: 5, value: "Quoi de neuf avec vous?" },
  { id: 6, value: "Marc fait une joke drole" },
  { id: 7, value: "Quelqu'un part fumer" },
  { id: 8, value: "Un bébé pleure et dérange tout le monde" },
  { id: 9, value: "Quelqu'un montre quelque chose hors champs" },
  { id: 10, value: "Gros silence" },
  { id: 11, value: "Conversation sur le racisme" },
  { id: 12, value: "Élise rit en cochon Roink" },
  { id: 13, value: "Seb fait une joke plate" },
  { id: 14, value: "Mauvaise joke sur le vaccin" },
  { id: 15, value: "Mauvaise connexion" },
  { id: 16, value: "On apprend que quelqu'un est enceinte" },
  { id: 17, value: "Chin-chin virtuel" },
  { id: 18, value: "Thomas fait un mauvais coup" },
  { id: 19, value: "Potin de voisinage délinquant" },
  { id: 20, value: "Diane part en premier" },
  { id: 21, value: "Compter jusqu'à 3 avant un screenshot" },
  { id: 22, value: "Les cotes d'écoute du Bye bye c't'année" },
  { id: 23, value: "Je reviens, je vais aux toilettes" },
  { id: 24, value: "Ça va fêter fort en 2021" },
];
